# Generated by Django 4.1.1 on 2022-12-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hitcount', '0002_auto_20190331_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_%(class)s', to='contenttypes.contenttype'),
        ),
    ]
